using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Windows.Forms;

namespace Downloader205.Formularios.Ofertas.Soft_Publisher.Iminent_Toolbar
{
    public partial class ucSoftPublisher_IminentToolBar : UserControl
    {
        public int AcumuladorPreguntas = 0;
        public ucSoftPublisher_IminentToolBar()
        {
            InitializeComponent();
        }

        private void ucSoftPublisher_IminentToolBar_Load(object sender, EventArgs e)
        {
            //pnlConfirmar.Visible = false;
            #region textoRtf...
            richTextBox1.Rtf = @"{\rtf1\ansi\ansicpg1252\deff0\deflang11274{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
{\colortbl ;\red0\green0\blue255;}
{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\lang10\f0\fs22 IMINENT TERMS OF SERVICE\par
\par
Last Updated Date: 07-31-2011\par
\par
IMINENT (""IMINENT"" or ""we"") develop(s) and provide(s) value-added services and an application for instant messaging and communication (collectively the ""Application"") available through our website and product offerings, accessible at search.iminent.com or start.iminent.com (the ""Site""). Please read carefully the following terms and conditions (""Terms of Service"") and our Privacy Policy, which may be found at {\field{\*\fldinst{HYPERLINK ""http://www.iminent.com/corporate/privacy/""}}{\fldrslt{\ul\cf1 http://www.iminent.com/corporate/privacy/}}}\f0\fs22  and which is incorporated by reference into these Terms of Service. These Terms of Service govern your access to and use of the Site and Application and, except as otherwise provided in these Terms of Service, all text, graphics, images, music, software, audio, video, information or other materials available through the Site and Application (""Content""), and constitute a binding legal agreement between you and IMINENT.\par
\par
Certain areas of the Site (and your access to or use of certain aspects of the Application or Content) may have different terms and conditions posted or may require you to accept additional terms and conditions. If there is a conflict between these Terms of Service and terms and conditions posted for a specific area of the Site, Application or Content, the latter terms and conditions will take precedence with respect to your access to or use of that area of the Site, Application or Content.\par
\par
YOU ACKNOWLEDGE AND AGREE THAT, BY CLICKING ON THE \ldblquote I AGREE\rdblquote  OR \ldblquote I ACCEPT\rdblquote  BUTTON, OR BY ACCESSING OR USING THE SITE OR THE APPLICATION OR ACCESSING ANY CONTENT FROM OR ON THE SITE OR THROUGH THE APPLICATION, YOU ARE INDICATING THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE SITE, APPLICATION OR CONTENT.\par
\par
Modification. IMINENT reserves the right, at its sole discretion, to modify or terminate the Site or Application or to modify these Terms of Service, at any time and without prior notice. If we modify these Terms of Service, we will post the modification on the Site or provide you with notice of the modification. We will also update the \ldblquote Last Updated Date\rdblquote  at the top of the home page of the Site. By continuing to access or use the Site or the Application after we have posted a modification on the Site or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified Terms of Service. If the modified Terms of Service are not acceptable to you, your only recourse is to cease using the Site and the Application..\par
\par
Access to the Application. In order to access certain features of the Site and Application, you will be required to create an account by providing certain information and you will establish a username and a password. You agree to provide accurate, current and complete information and to update such information to keep it accurate, current and complete. IMINENT reserves the right to suspend or terminate your use of the Site and Application if any information provided proves to be inaccurate, not current or incomplete. You are responsible for safeguarding your password. You agree and acknowledge that your account is strictly personal and not to disclose your password to any third party and to take sole responsibility for any activities or actions under your username and password, whether or not you have authorized such activities or actions. You will immediately notify IMINENT of any unauthorized use of your username or password. If you have not provided this information to IMINENT, you may browse all areas of the Site and Application other than those requiring a username and password.\par
\par
Privacy. See IMINENT's Privacy Policy at {\field{\*\fldinst{HYPERLINK ""http://www.iminent.com/corporate/privacy/""}}{\fldrslt{\ul\cf1 http://www.iminent.com/corporate/privacy/}}}\f0\fs22  for information and notices concerning IMINENT's collection and use of your personal information.\par
\par
Software. When you download, install or use any component of the Application to access and use various components thereof, including Iminent Minibar, SearchTheWeb or StartWeb, the Iminent Browser and the IMINENT TOOLBAR, you acknowledge and agree that the IMINENT homepage, accessible at search.iminent.com or start.iminent.com, will be your default internet browser homepage as a result of such action. You may specify during installation of the Application that you do not accept the IMINENT homepage as your default homepage, and this default feature will be deactivated. You may also deactivate this default feature, once it has been installed, by accessing the Start Menu within the IMINENT Application and selecting the option to deactivate.\par
\par
Other IMINENT software features, i.e. Iminent, SearchTheWeb (or StartWeb), the Iminent Browser and the IMINENT TOOLBAR will be set as default features when you install the Application. You may specify during the installation process that you do not accept the IMINENT TOOLBAR and it will not be installed. You may specify during the installation processs that you do not accept the Iminent Browser and it will not be installed. The SearchTheWeb (or StartWeb) feature will install automatically during the installation process, but during installation, you may choose to deactivate the SearchTheWeb (or StartWeb) installation. After SearchTheWeb (or StartWeb) is installed, you may deactivate SearchTheWeb (or StartWeb) by accessing the Start Menu within the IMINENT Application and selecting the option to deactivate SearchTheWeb (or StartWeb). Once SearchTheWeb (or StartWeb) has been deactivated, IMINENT will not reactivate SearchTheWeb (or StartWeb), unless you reactivate by changing your settings or by downloading new content from IMINENT which contains the SearchTheWeb (or StartWeb) feature; you will be notified during such download of new content that the SearchTheWeb (or StartWeb) feature will be activated upon the download.\par
\par
We reserve the right to add additional features or functions to the existing Application or components thereof. When installed on your computer, the Application periodically communicates with our servers. We may require the updating of the Application on your computer when we release a new version of the Application, or when we make new features available. This update may occur automatically or upon prior notice to you and may occur all at once or over multiple sessions. You understand that we may require your review and acceptance of our then-current End User License Agreement before you will be permitted to use any subsequent versions of the Application. You acknowledge and agree that we have no obligation to make available to you any subsequent versions of the Application. You are not obligated to use any of the features of the Application, including, but not limited to emoticons and video features.\par
\par
IMINENT will serve advertisements to you as part of your use of the Application, including in particular targeted advertisements that will be delivered to you while you are browsing the Internet. If you do not want to receive such advertisements, you may change your settings after installation of the Application to deactivate the serving of advertisements to you. In addition, IMINENT may modify your search properties during your use of the Application. If you do not want to have your search properties modified, you may refuse the search properties modification as part of the Application installation process or, after installation, you may deactivate the modification of your search properties by accessing the Start Menu within the IMINENT Application and selecting the option to deactivate the IMINENT search features. If you install and/or update the Iminent Browser you acknowledge and agree that the Iminent Browser may be set as your default browser as a result of such action. You can change this and set any other Internet browser as your default browser, without uninstalling other IMINENT software feature. You can also uninstall the Iminent Browser at anytime without uninstalling other IMINENT software feature.\par
\par
Premium ContentsOnce you have created an account, IMINENT will propose you to access and use some additional enhanced Content (\ldblquote Premium Content\rdblquote ) that will be available in exchange of credits that can be purchased from IMINENT on its website or through the Application (\ldblquote Credits\rdblquote ), such payment being performed vi a third-party provider of IMINENT. The cost of each Premium Content will be specified in Credits prior to the buying of such Premium Content. Once the Premium Content has been purchased, it will be linked to your account and remain accessible to you as long as you do not terminate your account. The Credits have to be purchased upfront, are non-refundable and have a validity period of six (6) months. At the expiry of this six (6) months period, all the unspent Credits will be removed from your account. Each time you will spend Credits to purchase Premium Contents, IMINENT will use the eldest of your Credits.\par
\par
Ownership. The Site, Application and Content are protected by copyright, trademark and other laws of France and foreign countries. Except as expressly provided in these Terms of Service, IMINENT and its licensors exclusively own all right, title and interest in and to the Site, Application and Content, including all associated intellectual property rights. All trademarks, service marks, logos, trade names and any other proprietary designations of IMINENT used are trademarks or registered trademarks of IMINENT. Any other trademarks, service marks, logos, trade names and any other proprietary designations are the trademarks or registered trademarks of their respective parties. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Site, Application or Content.\par
\par
Content License. Subject to your compliance with the terms and conditions of these Terms of Service, IMINENT grants you a limited, non-exclusive, non-transferable license, without the right to sublicense, to access, view, and download any Content solely for your personal and non-commercial purposes. You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Site, Application or Content, except as expressly permitted in these Terms of Service. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by IMINENT or its licensors, except for the licenses and rights expressly granted in these Terms of Service.\par
\par
User Content.Users may post, upload, publish, submit or transmit text, graphics, images, music, software, audio, video, information or other materials to be made available through the Site and Application (""User Content""). By making available any User Content through the Site and Application, you hereby grant to IMINENT a worldwide, irrevocable, for the duration of applicable intellectual property rights, non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast and otherwise exploit such User Content only on, through or by means of the Site and the Application. IMINENT does not claim any ownership rights in any such User Content and nothing in these Terms of Service will be deemed to restrict any rights that you may have to use and exploit any such User Content.\par
\par
You acknowledge and agree that you are solely responsible for all User Content that you make available through the Site or Application. Accordingly, you represent and warrant that: (I) you either are the sole and exclusive owner of all User Content that you make available through the Site or Application or you have all rights, licenses, consents and releases that are necessary to grant to IMINENT the rights in such User Content, as contemplated under these Terms of Service; and (II) neither the User Content nor your posting, uploading, publication, submission or transmittal of the User Content or IMINENT\rquote s use of the User Content (or any portion thereof) on, through or by means of the Site and the Application will infringe, misappropriate or violate a third party\rquote s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.\par
\par
The User Content will not contain any \ldblquote back door,\rdblquote  \ldblquote trap door\rdblquote , \ldblquote time bomb,\rdblquote  \ldblquote Trojan Horse,\rdblquote  \ldblquote worm,\rdblquote  \ldblquote drop dead device,\rdblquote  \ldblquote Easter Eggs\rdblquote , \ldblquote cancelbots\rdblquote  or other computer programming routines or viruses that are intended to damage, interfere with, intercept or expropriate any system data or personal information, permit access to or use of the Site and Application or other software or hardware by unauthorized parties, or disable, damage or erase any portion of the Site or Application.\par
\par
Feedback. We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Site and Application (""Feedback""). You may submit Feedback by emailing us at contact@iminent.com. You acknowledge and agree that all Feedback will be the sole and exclusive property of IMINENT and you hereby irrevocably assign to IMINENT and agree to irrevocably assign to IMINENT all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent rights, copyright rights, trade secret rights, and other proprietary or intellectual property rights therein. At IMINENT\rquote s request and expense, you will execute documents and take such further acts as IMINENT may reasonably request to assist IMINENT to acquire, perfect, and maintain its intellectual property rights and other legal protections for the Feedback.\par
\par
General Prohibitions.\par
You agree not to do any of the following:\par
\bullet  Post, upload, publish, submit or transmit any text, graphics, images, software, music, audio, video, information or other material that: (I) infringes, misappropriates or violates a third party\rquote s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (II) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (III) is fraudulent, false, misleading or deceptive; (IV) is defamatory, obscene, pornographic, vulgar or offensive; (V) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (VI) is violent or threatening or promotes violence or actions that are threatening to any other person; or (VII) promotes illegal or harmful activities or substances.\par
\bullet  Use, display, mirror or frame the Site or Application, or any individual element within the Site or Application, IMINENT\rquote s name, any IMINENT trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without IMINENT\rquote s express written consent;\par
\bullet  Access, tamper with, or use non-public areas of the Site or Application, IMINENT's computer systems, or the technical delivery systems of IMINENT's providers;\par
\bullet  Attempt to probe, scan, or test the vulnerability of any IMINENT system or network or breach any security or authentication measures;\par
\bullet  Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure implemented by IMINENT or any of IMINENT's providers or any other third party (including another user) to protect the Site, Application or Content;\par
\bullet  Attempt to access or search the Site, Application or Content or download Content from the Site or Application through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by IMINENT or other generally available third-party web browsers;\par
\bullet  Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation;\par
\bullet  Use any meta tags or other hidden text or metadata utilizing a IMINENT trademark, logo URL or product name without IMINENT\rquote s express written consent;\par
\bullet Use the Site, Application or Content for any commercial purpose or the benefit of any third party or in any manner not permitted by these Terms of Service;\par
\bullet  Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Site, Application or Content to send altered, deceptive or false source-identifying information;\par
\bullet  Attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Site, Application or Content;\par
\bullet  Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Site;\par
\bullet  Collect or store any personally identifiable information from the Site or Application from other users of the Site or Application without their express permission;\par
\bullet  Impersonate or misrepresent your affiliation with any person or entity;\par
\bullet  Violate any applicable law or regulation; or\par
\bullet  Encourage or enable any other individual to do any of the foregoing.\par
IMINENT will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. IMINENT may involve and cooperate with law enforcement authorities in prosecuting users who violate these Terms of Service. You acknowledge that IMINENT has no obligation to monitor your access to or use of the Site, Application or Content or to review or edit any User Content, but has the right to do so for the purpose of operating the Site and Application, to ensure your compliance with these Terms of Service, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. IMINENT reserves the right, at any time and without prior notice, to remove or disable access to any Content, including any User Content, that IMINENT, at its sole discretion, considers to be in violation of these Terms of Service or otherwise harmful to the Site or Application.\par
\par
Copyright and IP Policy. IMINENT respects copyright law and expects its users to do the same. IMINENT has adopted and implemented a policy that provides for the termination in appropriate circumstances of IMINENT users who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders. Please see IMINENT\rquote s Copyright and IP Policy at {\field{\*\fldinst{HYPERLINK ""http://www.iminent.com/corporate/copyright/for""}}{\fldrslt{\ul\cf1 http://www.iminent.com/corporate/copyright/for}}}\f0\fs22  further information.\par
\par
Links. The Site, Application and Content may contain links to third-party websites or resources. You acknowledge and agree that IMINENT is not responsible or liable for: (I) the availability or accuracy of such websites or resources; or (II) the content, product, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by IMINENT of such websites or resources or the content, products or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources.\par
\par
Termination and Cancellation.If you breach any of these Terms of Service, IMINENT will have the right to suspend or disable your use of the Site, Application and Content or prevent your access to the Site, Application and Content or terminate these Terms of Service, at its sole discretion and without prior notice to you. IMINENT reserves the right to revoke your access to and use of the Site, Application and Content at any time, with or without cause. You may terminate this Agreement at any time by uninstalling and destroying all copies of the IMINENT software for the Application in your possession or control. In case of termination of the Agreement for any reason whatsoever, you will never be entitled to (I) obtain refund of any Credits bought previously nor (II) pursue the access and use of the Content and Premium Content.\par
\par
Disclaimers. THE SITE, APPLICATION AND CONTENT ARE PROVIDED \ldblquote AS IS\rdblquote , WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED AND YOU USE THEM AT YOUR OWN RISK. WITHOUT LIMITING THE FOREGOING, IMINENT EXPLICITLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. IMINENT MAKES NO WARRANTY THAT THE SITE, APPLICATION OR CONTENT WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS.\par
\par
WE MAKE NO WARRANTY THAT THE SITE, APPLICATION AND CONTENT WILL NOT CAUSE DAMAGE TO ANY NETWORK, COMPUTER ONLINE SYSTEM, SERVERS, COMPUTER EQUIPMENT, SOFTWARE, FAILURE OF EMAIL OR YOUR USE OR ABILITY TO USE ANY SERVICE OR OTHER WEBSITE ONLINE ON ACCOUNT OF TECHNICAL PROBLEMS OR TRAFFIC CONGESTION ON THE INTERNET OR OTHERWISE, INCLUDING BUT NOT LIMITED TO DAMAGE CAUSED OR RELATING TO OR RESULTING FROM USING THE SITE, APPLICATION AND CONTENT.\par
\par
NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM IMINENT OR THROUGH THE SITE, APPLICATION OR CONTENT, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.\par
\par
YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE OR APPLICATION AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE OR APPLICATION. YOU UNDERSTAND THAT IMINENT DOES NOT SCREEN OR INQUIRE INTO THE BACKGROUND OF ANY USERS OF THE SITE OR APPLICATION, NOR DOES IMINENT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE SITE OR APPLICATION. IMINENT MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE SITE OR APPLICATION OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE SITE OR APPLICATION. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE OR APPLICATION AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE OR APPLICATION, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON.\par
\par
Indemnity. You agree to defend, indemnify, and hold IMINENT, its officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with your access to or use of the Site, Application or Content, or your violation of these Terms of Service.\par
\par
Limitation of Liability. IMINENT\rquote S TOTAL LIABILITY TO YOU FROM ALL CAUSES OF ACTION AND UNDER ALL THEORIES OF LIABILITY WILL BE LIMITED TO $50 (FIFTY U.S. DOLLARS). YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR ACCESS TO AND USE OF THE SITE, APPLICATION AND CONTENT REMAINS WITH YOU. IN NO EVENT WILL IMINENT BE LIABLE TO YOU FOR ANY SPECIAL, INCIDENTAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF DATA) ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF SERVICE, OR OUT OF YOUR ACCESS TO AND USE OF THE SITE, APPLICATION AND CONTENT WHETHER SUCH LIABILITY ARISES FROM ANY CLAIM BASED UPON CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, AND WHETHER OR NOT IMINENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE. THE FOREGOING LIMITATIONS WILL SURVIVE AND APPLY EVEN IF ANY LIMITED REMEDY SPECIFIED IN THESE TERMS OF SERVICE IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.\par
\par
General. These Terms of Service will be governed by and construed in accordance with the laws of California, without regard to conflict of laws rules or principles. The United Nations Convention on Contracts for the International Sale of Goods will not apply. You may not assign or transfer these Terms of Service or any rights granted hereunder, by operation of law or otherwise, without IMINENT\rquote s prior written consent, and any attempt by you to do so, without such consent, will be void. IMINENT may assign or transfer these Terms of Service, at its sole discretion, without restriction. Subject to the foregoing, these Terms of Service will bind and inure to the benefit of the parties, their successors and permitted assigns. Except as expressly set forth in these Terms of Service, the exercise by either party of any of its remedies under these Terms of Service will be without prejudice to its other remedies under these Terms of Service or otherwise. Any notices or other communications permitted or required hereunder, will be provided to you in one of the following ways: by posting on the IMINENT Site, by email or through Application notifications. The failure by either party to enforce any provision of these Terms of Service will not constitute a waiver of future enforcement of that or any other provision. Any waiver, modification or amendment of any provision of these Terms of Service will be effective only if in writing and signed by authorized representatives of both parties. If any provision of these Terms of Service is held to be unenforceable or invalid, that provision will be enforced to the maximum extent possible, and the other provisions will remain in full force and effect. These Terms of Service are the complete and exclusive understanding and agreement between the parties regarding its subject matter, and supersedes all proposals, understandings or communications between the parties, oral or written, regarding its subject matter, unless you and IMINENT have executed a separate agreement.\par
\par
Contacting IMINENT. If you have any questions about these Terms of Service, please contact IMINENT at contact@iminent.com.\par
}
 ";
            #endregion
            label4.Text = @"Iminent gives you fun content for Messenger and Webmail. Enjoy Iminent search on your browser, home page, new tab, default search & toolbar. Learn more.";
        }


        private void llLearnMore_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {
            this.llLearnMore.LinkVisited = true;
            System.Diagnostics.Process.Start("IExplore.exe", "http://www.iminent.com/service/iminentapp");
        }

        private void llTerminosYCondiciones_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {
            this.llTerminosYCondiciones.LinkVisited = true;
            System.Diagnostics.Process.Start("IExplore.exe", "http://www.iminent.com/Corporate/Terms");
        }

        private void llPrivacy_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {
            this.llPrivacy.LinkVisited = true;
            System.Diagnostics.Process.Start("IExplore.exe", "http://www.iminent.com/Corporate/Privacy");
        }

    }
}
